name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Test homework1
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y python3-tk
        ./build_python_virtual_env.sh
        source opencvdl/bin/activate
        python ./homework/hw1/hw1.py
    - name: Test with pytest
      run: |
        pip install pytest
